"""
Import-smoke tests for every submodule of every moseq2 package in the container.

If any of these fail during `docker build`, the build fails. The vast majority
of "container built fine, dies on first `import` in Jupyter" bugs are caught
here: click default-shape mismatches, removed numpy internals (umath_tests,
inner1d), tifffile / h5py / scikit-image ABI drift, etc.

Pure import-time only — no data fixtures, no I/O.
"""

import importlib

import pytest

MODULES = [
    # pybasicbayes
    "pybasicbayes",
    "pybasicbayes.abstractions",
    "pybasicbayes.distributions",
    "pybasicbayes.distributions.gaussian",
    "pybasicbayes.distributions.regression",
    "pybasicbayes.distributions.geometric",
    "pybasicbayes.distributions.negativebinomial",
    "pybasicbayes.distributions.poisson",
    "pybasicbayes.distributions.multinomial",
    "pybasicbayes.distributions.uniform",
    "pybasicbayes.distributions.binomial",
    "pybasicbayes.distributions.meta",
    "pybasicbayes.models",
    "pybasicbayes.models.factor_analysis",
    "pybasicbayes.models.mixture",
    "pybasicbayes.models.parallel_mixture",
    "pybasicbayes.util",
    "pybasicbayes.util.general",
    "pybasicbayes.util.plot",
    "pybasicbayes.util.stats",
    "pybasicbayes.util.text",
    "pybasicbayes.util.testing",
    "pybasicbayes.util.profiling",
    "pybasicbayes.util.cyutil",
    # pyhsmm
    "pyhsmm",
    "pyhsmm.models",
    "pyhsmm.parallel",
    "pyhsmm.basic",
    "pyhsmm.basic.abstractions",
    "pyhsmm.basic.distributions",
    "pyhsmm.basic.models",
    "pyhsmm.internals",
    "pyhsmm.internals.hmm_states",
    "pyhsmm.internals.hsmm_states",
    "pyhsmm.internals.hsmm_inb_states",
    "pyhsmm.internals.initial_state",
    "pyhsmm.internals.transitions",
    "pyhsmm.util",
    "pyhsmm.util.general",
    "pyhsmm.util.plot",
    "pyhsmm.util.stats",
    "pyhsmm.util.text",
    "pyhsmm.util.testing",
    "pyhsmm.util.profiling",
    # pyhsmm-autoregressive
    "autoregressive",
    "autoregressive.models",
    "autoregressive.distributions",
    "autoregressive.util",
    # moseq2-extract
    "moseq2_extract",
    "moseq2_extract.cli",
    "moseq2_extract.gui",
    "moseq2_extract.util",
    "moseq2_extract.io",
    "moseq2_extract.io.image",
    "moseq2_extract.io.video",
    "moseq2_extract.extract",
    "moseq2_extract.extract.extract",
    "moseq2_extract.extract.proc",
    "moseq2_extract.extract.roi",
    "moseq2_extract.extract.track",
    "moseq2_extract.helpers",
    "moseq2_extract.helpers.data",
    "moseq2_extract.helpers.extract",
    "moseq2_extract.helpers.wrappers",
    # moseq2-pca
    "moseq2_pca",
    "moseq2_pca.cli",
    "moseq2_pca.gui",
    "moseq2_pca.util",
    "moseq2_pca.viz",
    "moseq2_pca.pca",
    "moseq2_pca.pca.util",
    "moseq2_pca.helpers",
    "moseq2_pca.helpers.data",
    "moseq2_pca.helpers.wrappers",
    # moseq2-viz
    "moseq2_viz",
    "moseq2_viz.cli",
    "moseq2_viz.gui",
    "moseq2_viz.util",
    "moseq2_viz.viz",
    "moseq2_viz.io",
    "moseq2_viz.io.video",
    "moseq2_viz.info",
    "moseq2_viz.info.util",
    "moseq2_viz.scalars",
    "moseq2_viz.scalars.util",
    "moseq2_viz.model",
    "moseq2_viz.model.util",
    "moseq2_viz.model.stat",
    "moseq2_viz.model.dist",
    "moseq2_viz.model.embed",
    "moseq2_viz.model.trans_graph",
    "moseq2_viz.model.fingerprint_classifier",
    "moseq2_viz.helpers",
    "moseq2_viz.helpers.wrappers",
    # moseq2-model
    "moseq2_model",
    "moseq2_model.cli",
    "moseq2_model.gui",
    "moseq2_model.util",
    "moseq2_model.train",
    "moseq2_model.train.models",
    "moseq2_model.train.util",
    "moseq2_model.helpers",
    "moseq2_model.helpers.data",
    "moseq2_model.helpers.wrappers",
    # moseq2-app
    "moseq2_app",
    "moseq2_app.main",
    "moseq2_app.util",
    "moseq2_app.roi",
    "moseq2_app.roi.controller",
    "moseq2_app.roi.view",
    "moseq2_app.roi.widget",
    "moseq2_app.roi.validation",
    "moseq2_app.scalars",
    "moseq2_app.scalars.controller",
    "moseq2_app.scalars.widgets",
    "moseq2_app.flip",
    "moseq2_app.flip.widget",
    "moseq2_app.flip.train",
    "moseq2_app.viz",
    "moseq2_app.viz.controller",
    "moseq2_app.viz.view",
    "moseq2_app.viz.widgets",
    "moseq2_app.stat",
    "moseq2_app.stat.controller",
    "moseq2_app.stat.view",
    "moseq2_app.stat.widgets",
    "moseq2_app.gui",
    "moseq2_app.gui.progress",
    "moseq2_app.gui.widgets",
    "moseq2_app.gui.wrappers",
]


@pytest.mark.parametrize("modname", MODULES, ids=MODULES)
def test_import(modname):
    importlib.import_module(modname)
