name: Build SIF

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "v06.6"

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build SIF
        run: |
          apptainer build \
            moseq.sif \
            docker://ghcr.io/athp18/moseq:${{ github.event.inputs.tag }}

      - name: Inspect SIF
        run: |
          ls -lh moseq.sif
          apptainer inspect moseq.sif

      - name: Upload SIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: moseq-${{ github.event.inputs.tag }}.sif
          path: moseq.sif
          retention-days: 7